#+TITLE: 分散分析
#+SUBTITLE: 第12講 - 複数のグループ間の違いを検証する
#+AUTHOR: 村田 昇
#+EMAIL: noboru.murata@gmail.com
#+DATE: 
#+STARTUP: hidestars content indent
# Time-stamp: <2024-06-21 13:49:24 mura>
:REVEAL:
#+SETUPFILE: "./reveal.js/org/mycourse.org"
# C-c C-x C-v でinlineを切り替え
# <m C-i でlatex block (math env用)
# C-c '
:END:

* COMMENT メモ
- 修正事項
- 水準 A_i とする必要はなさそう (二元の問題のためであった)
- MC実験のところは整理してわかりやすく
  
* 講義概要
- 分散分析とは
- 一元配置
  - 一元配置のモデル
  - 検定の構成
- 二元配置
  - 二元配置のモデル
  - 検定の構成

#+begin_src R :exports none :tangle no
  setwd("~/Desktop/lectures/u-tokyo/spring/course")
#+end_src
#+begin_src R :exports none
  ### 第12講 サンプルコード
  library(tidyverse)
  #' 日本語を用いる場合 macOS では以下の設定を行うと良い
  if(Sys.info()["sysname"] == "Darwin") { # macOS か調べて日本語フォントを指定
    theme_update(text = element_text(family = "HiraginoSans-W4"))
    update_geom_defaults("text", list(family = theme_get()$text$family))
    update_geom_defaults("label", list(family = theme_get()$text$family))}
#+end_src


* 分散分析とは
** 分散分析
- 平均の差の検定 \\
  *2つのグループ間* で平均の差があるか否か
- 分散分析 \\
  *2つ以上のグループ間* で平均の差があるか否か
- [[color:green][分散分析における仮説の例]]
  #+begin_quote
  - ある小売店について"売上高は月によって差があるか"
  - ある銘柄の株価について"収益率は曜日によって差があるか"
  #+end_quote

** 基本的な考え方
- データの変動 (*分散*) =不確定性 を分解 
  - グループ間での変動
  - 観測誤差のみに起因する変動
- 変動の大きさを比較 
  - 平均に差がない : 自由度を除いて両者に本質的な差がない
  - 平均に差がある : グループ間の変動が増してより大きくなる
- 分散分析は *"データの変動の分析"*


* 分散の比の検定 (再掲)
** 分散の比の検定
- 2種類のデータの分散が等しいか否かを検定する
  #+begin_quote
  \begin{equation}
    H_0:\sigma_1^2=\sigma_2^2\quad\text{vs}\quad H_1:\sigma_1^2\neq\sigma_2^2
  \end{equation}
  #+end_quote

** 考え方
- \(X_1,\dotsc,X_m\) および \(Y_1,\dotsc,Y_n\)
  の不偏分散: \(s_1^2\), \(s_2^2\)
  # - \(X_1,\dotsc,X_m\) の不偏分散: \(s_1^2\)
  # - \(Y_1,\dotsc,Y_n\) の不偏分散: \(s_2^2\)
  - このとき \(s_1^2,s_2^2\) は独立でそれぞれ
    - \((m{-}1)s_1^2/\sigma_1^2\)
      は自由度 \(m{-}1\) の \(\chi^2\) 分布に従う
    - \((n{-}1)s_2^2/\sigma_2^2\)
      は自由度 \(n{-}1\) の \(\chi^2\) 分布に従う
  - *\(F\) 検定*
    #+begin_quote
    \begin{equation}
      \text{検定統計量 : }
      F=\frac{s_1^2}{s_2^2}
      \left(
        =
        \frac
        {((m{-}1)s_1^2/\sigma_1^2)/(m{-}1)}
        {((n{-}1)s_2^2/\sigma_2^2)/(n{-}1)}
      \right)
    \end{equation}
    #+end_quote
    - 帰無分布は自由度 \(m{-}1,n{-}1\) の \(F\) 分布

** 両側検定の棄却域
- 有意水準を選択 : \(\alpha\in(0,1)\)
- \(H_0\) の下では以下が成立
  #+begin_quote
  \begin{equation}
    P(F < F_{\alpha/2}(m{-}1,n{-}1)
    \text{ または }F > F_{1{-}\alpha/2}(m{-}1,n{-}1))=\alpha
  \end{equation}
  #+end_quote
  - 自由度 \(m{-}1,n{-}1\) の \(F\) 分布
    - \(F_{\alpha/2}(m{-}1,n{-}1)\) : \(\alpha/2\) 分位点
    - \(F_{1{-}\alpha/2}(m{-}1,n{-}1)\) : \(1{-}\alpha/2\) 分位点
- 第一種過誤の上限が \(\alpha\) の棄却域
  #+begin_quote
  \begin{equation}
    R_{\alpha}=
    \left(-\infty,F_{\alpha/2}(m{-}1,n{-}1)\right)
    \cup\left(F_{1{-}\alpha/2}(m{-}1,n{-}1),\infty\right)
  \end{equation}
  #+end_quote

#+reveal: split
- データから検定統計量 \(F\) の値を計算
- 以下の場合，帰無仮説を棄却
  #+begin_quote
  \begin{equation}
    F < F_{\alpha/2}(m{-}1,n{-}1)
    \quad\text{または}\quad
    F>F_{1{-}\alpha/2}(m{-}1,n{-}1)
  \end{equation}
  #+end_quote


* 一元配置
** 一元配置の問題設定
- グループ分けが1種類 : \(p\) グループ
  \(A_1,A_2,\dotsc,A_p\)
  # #+begin_quote
  #   \begin{equation}
  #     A_1,A_2,\dotsc,A_p
  #   \end{equation}
  # #+end_quote
- 各グループ \(i\) ごとに \(n_i\) 個のデータを観測
  #+begin_quote
  \begin{equation}
    Y_{i1},Y_{i2},\dotsc,Y_{in_i},\quad (i=1,2,\dotsc,p)
  \end{equation}
  #+end_quote
- [[color:green][小売店の売上高の問題]]
  #+begin_quote
  - \(A_1,A_2,\dotsc,A_p\) : 月
  - \(Y_{i1},Y_{i2},\dotsc,Y_{in_i}\) : \(i\) 月の各日における売上高
  #+end_quote

** 一元配置のモデル
- 分散分析の用語
  - *因子* : グループ分けのこと ([[color:green][月ごと]])
  - *水準* : 因子内の各グループのこと ([[color:green][1月，2月，3月，…]])
- 観測データのモデル
  #+begin_quote
  \begin{equation}
    Y_{ij}=\mu_i+\varepsilon_{ij}\quad(i=1,\dotsc,p;\;j=1,\dotsc,n_i).
  \end{equation}
  #+end_quote
- モデルの仮定
  - 水準 \(A_i\) における観測データの平均値 \(\mu_i\) は定数
  - \(\varepsilon_{ij}\) は独立同分布 (平均0, 分散 \(\sigma^2\) の正規分布)

** 一元配置の検定
- 検定問題
  #+begin_quote
  各水準 \(A_1,A_2,\dotsc,A_p\)
  の平均 \(\mu_1,\mu_2,\dotsc,\mu_{p}\)
  に差があるか否かを検定する
  #+end_quote
  - 帰無仮説 : 全ての水準で平均に差はない
  - 対立仮説 : 平均の異なる水準がある
  #+begin_quote
  \begin{equation}
    H_0:\mu_1=\cdots=\mu_p\quad\text{vs}\quad
    H_1:\text{ある\(i,j\)に対して}\mu_i\neq\mu_j.
  \end{equation}
  #+end_quote

** 分析の考え方
- データの変動から因子間での変動と観測誤差の変動を抽出して比較
- 各種平均 (\(n=\sum_{i=1}^pn_i\) は全サンプル数)
  #+begin_quote
  \begin{align}
    &\text{(全データの標本平均)}
    &\bar{Y}_{\cdot\cdot}&=\frac{1}{n}\sum_{i=1}^p\sum_{j=1}^{n_i}Y_{ij},\\
    &\text{(水準\(A_i\)の標本平均)}
    &\bar{Y}_{i\cdot}&=\frac{1}{n_i}\sum_{j=1}^{n_i}Y_{ij}\quad
                       (i=1,\dotsc,p).
  \end{align}
  #+end_quote

#+reveal: split
- 各種変動
  #+begin_quote
  \begin{align}
    &\text{(全変動)}
    &SS_T&=\sum_{i=1}^p\sum_{j=1}^{n_i}(Y_{ij}-\bar{Y}_{\cdot\cdot})^2,\\
    &\text{(級内変動)}
    &SS_W&=\sum_{i=1}^p\sum_{j=1}^{n_i}(Y_{ij}-\bar{Y}_{i\cdot})^2,\\
    &\text{(級間変動)}
    &SS_B&=\sum_{i=1}^p\sum_{j=1}^{n_i}(\bar{Y}_{i\cdot}-\bar{Y}_{\cdot\cdot})^2
           =\sum_{i=1}^pn_i(\bar{Y}_{i\cdot}-\bar{Y}_{\cdot\cdot})^2.
  \end{align}
  #+end_quote
  - *級内変動* : 各水準内でのデータの変動の合計 (観測誤差に起因)
  - *級間変動* : 水準間でのデータの変動の合計 (水準ごとのデータ数で重みづけ)

#+reveal: split
- 変動の分解
  #+begin_quote
  \begin{equation}
    \underbrace{\text{(全変動) }SS_T}_{\text{自由度 }n{-}1}
    =\underbrace{\text{(級内変動) }SS_W}_{\text{自由度 }n{-}p}
    +\underbrace{\text{(級間変動) }SS_B}_{\text{自由度 }p{-}1}
  \end{equation}
  #+end_quote
- 帰無仮説 \(H_0\) が正しい場合
  - 水準内・水準間でのデータの変動はともに観測誤差が原因
  - 自由度を除けば本質的な違いはない
  - \(SS_T/(n{-}1)\) は \(\sigma^2\) の不偏推定量
  - \(SS_W/(n{-}p)\), \(SS_B/(p{-}1)\) もともに \(\sigma^2\) の不偏推定量

#+reveal: split
- 変動の分解
  #+begin_quote
  \begin{equation}
    \underbrace{\text{(全変動) }SS_T}_{\text{自由度 }n{-}1}
    =\underbrace{\text{(級内変動) }SS_W}_{\text{自由度 }n{-}p}
    +\underbrace{\text{(級間変動) }SS_B}_{\text{自由度 }p{-}1}
  \end{equation}
  #+end_quote
- 対立仮説 \(H_1\) が正しい場合
  - 水準間での変動 \(SS_B\) は観測誤差と平均値の差に影響される
  - \(SS_B\) は \(SS_W\) より本質的に大きくなる

** 一元配置の検定
- 検定統計量
  #+begin_quote
  \begin{equation}
    F=\frac{SS_B/(p{-}1)}{SS_W/(n{-}p)}
  \end{equation}
  #+end_quote
- 帰無仮説の下で次の事実が成り立つ
  - \(SS_B,SS_W\) は独立
  - \(SS_B\) は自由度 \(p{-}1\) の \(\chi^2\) 分布に従う
  - \(SS_W\) は自由度 \(n{-}p\) の \(\chi^2\) 分布に従う
- 帰無分布は自由度 \(p{-}1,n{-}p\) の \(F\) 分布に従う
- 対立仮説の下 \(F\) は大きな値をとるので右片側検定

** 棄却域を用いる場合
- 有意水準を選択 : \(\alpha\in(0,1)\)
- 自由度 \(p{-}1,n{-}p\) の \(F\) 分布
  - \(F_{1{-}\alpha}(p{-}1,n{-}p)\) : \(1{-}\alpha\) 分位点
- \(H_0\) の下で以下が成立
  #+begin_quote
  \begin{equation}
    P(F>F_{1{-}\alpha}(p{-}1,n{-}p))=\alpha
  \end{equation}
  #+end_quote
- 第一種過誤の上限が \(\alpha\) となる棄却域
  #+begin_quote
  \begin{equation}
    R_{\alpha}=
    \left(F_{1{-}\alpha}(p{-}1,n{-}p),\infty\right)
  \end{equation}
  #+end_quote

#+reveal: split
- データから検定統計量 \(F\) の値を計算
- 以下の場合，帰無仮説を棄却
  #+begin_quote
  \begin{equation}
    F>F_{1{-}\alpha}(p{-}1,n{-}p)
  \end{equation}
  #+end_quote

** @@latex:@@\(p\) 値を用いる場合
- \(p\) 値を計算 (右片側検定の場合の計算方法)
  #+begin_quote
  \begin{equation}
    \text{(\(p\) 値)}=\int_{F}^\infty f(x)dx
  \end{equation}
  #+end_quote
  - \(f(x)\) は自由度 \(p{-}1,n{-}p\) の \(F\) 分布の確率密度
- \(p\) 値が \(\alpha\) 未満なら帰無仮説を棄却

** 分散分析表 (一元配置の場合)
|--------+-----------+----------+------------------+----------+--------------------------------------+---|
|        | 自由度    | 平方和   | 平均平方和       | \(F\) 値 | \(p\) 値                             |   |
|--------+-----------+----------+------------------+----------+--------------------------------------+---|
| 級間   | \(p{-}1\) | \(SS_B\) | \(SS_B/(p{-}1)\) | \(F\)    | \(\mathstrut\int_{F}^\infty f(x)dx\) |   |
| 級内   | \(n{-}p\) | \(SS_W\) | \(SS_W/(n{-}p)\) |          |                                      |   |
|--------+-----------+----------+------------------+----------+--------------------------------------+---|
| 全変動 | \(n{-}1\) | \(SS_T\) |                  |          |                                      |   |
|--------+-----------+----------+------------------+----------+--------------------------------------+---|
- \(f(x)\) は自由度 \(p{-}1,n{-}p\) の \(F\) 分布の確率密度

** モデルの別表現
- 各水準の平均値の相対効果による定式化
  - 因子 \(A\) 全体の平均効果 : \(\mu\)
  - 平均 \(\mu\) を基準とした各水準 \(A_i\) の相対的な効果 : \(\alpha_i\)
  - 平均値の別表現
    #+begin_quote
    \begin{equation}
      \mu_i=\mu+\alpha_i,\quad
      \mu=\frac{1}{n}\sum_{i=1}^pn_i\mu_i,\quad
      \sum_{i=1}^pn_i\alpha_i=0
    \end{equation}
    #+end_quote
- 帰無仮説 \(H_0\) は以下と同等
  #+begin_quote
  \begin{equation}
    H_{0}:\alpha_1=\cdots=\alpha_p=0
  \end{equation}
  #+end_quote

** 分散分析の計算
- 基本書式 
  #+begin_src R :eval no :tangle no
    aov(formula, data)
    #' formula: 式，一元配置の場合は (観測値 ~ 因子)
    #' data: データフレーム
    #' 分析の結果を参照する関数がいくつかあるので，多くの場合適当なオブジェクトに代入
  #+end_src
- 分散分析表の表示
  #+begin_src R :eval no :tangle no
    aov(formula, data) |> summary()     # 分析表形式での表示
    aov(formula, data) |> anova()       # データフレーム(data.frame形式)
    aov(formula, data) |> broom::tidy() # データフレーム(tibble形式)
    aov(formula, data) |> model.table(type = "means")   # 平均値
    aov(formula, data) |> model.table(type = "effects") # 効果(既定値)
  #+end_src

** 分散分析の計算 (検定のみ)
- 基本書式 
  #+begin_src R :eval no :tangle no
    oneway.test(formula, data, subset, na.action, var.equal = FALSE)
    #' formula: 式
    #' data: データフレーム
    #' subset: subsetの指定
    #' na.action: 欠損値の扱い
    #' var.equal: 等分散を仮定する場合は TRUE，標準では Welch の近似が用いられる
  #+end_src


* 実習
:PROPERTIES:
:reveal_background: #fef4f4
:END:
** 練習問題
:PROPERTIES:
:reveal_background: #fef4f4
:END:
- 一元配置分散分析について確率シミュレーションを行いなさい．
- 東京の気候データ (~tokyo_weather.csv~) の
  気温の項目について以下の問に答えよ．
  - 曜日ごとの気温の平均と分散を求めよ．
    #+begin_src R :eval no :tangle no
      #' 週日を因子(factor)とするには例えば以下のような項目を加えればよい
      tw_data <- read_csv("data/tokyo_weather.csv")
      days <- with(tw_data, # 日付を取り出して整形する
                   as.Date(paste(year,month,day,sep="-"))) 
      wdays <- weekdays(days) # 各日付の曜日を計算
      tw_data <- cbind(tw_data, weekday=as.factor(wdays)) # 曜日因子を追加
    #+end_src
  - 曜日ごとに平均が異なるといえるかどうか分散分析を用いて検定しなさい．

#+begin_src R :eval no :exports none
  #' ---------------------------------------------------------------------------
  #' @practice 分散分析(一元配置)の Monte-Carlo 実験の例
  #'
  #' A,B,Cの3つの水準をもつデータを考える
  fact <- as.factor(rep(LETTERS[1:3], c(10,8,12))) # 因子(水準A,B,Cが10,8,12個)
  toy_data0 <- # 平均が全て等しい場合 (帰無仮説が正しい例)
    tibble(factor = fact,                                 # 水準
           value = rnorm(length(fact), mean = 3, sd = 2)) # 観測値
  #' データの状況を図示する
  toy_data0 |>
    ggplot(aes(x = factor, y = value)) +
    geom_boxplot(fill = "pink") +
    geom_jitter(colour = "red", width = 0.2) +
    labs(title = "帰無仮説が正しい場合")
  #' 
  alt <- rep(c(1,-1,1), c(10,8,12)) # 水準ごとの平均のずれ(対立仮説の例)
  toy_data1 <- # 平均が水準ごとに異なる場合(対立仮説が正しい例)
    tibble(factor = fact,                                       # 水準
           value = rnorm(length(fact), mean = 3, sd = 2) + alt) # 観測値
  #' 同様に図示する
  toy_data1 |>
    ggplot(aes(x = factor, y = value)) +
    geom_boxplot(fill = "lightblue") +
    geom_jitter(colour = "blue", width = 0.2) +
    labs(title = "帰無仮説が誤りの場合")
  #'
  #' 分散分析を行う
  #' 帰無仮説が正しい場合
  aov(value ~ factor, data = toy_data0) 
  aov(value ~ factor, data = toy_data0) |>
    broom::tidy() # 分散分析表
  #' 帰無仮説が誤りの場合(対立仮説が正しい場合)
  aov(value ~ factor, data = toy_data1) 
  aov(value ~ factor, data = toy_data1) |>
    broom::tidy() # 分散分析表
  #'
  #' @notes
  #' 関数 aov() のようにデータが第1引数でない場合にパイプ演算子を使うには
  #' "_" (placeholder) を使って位置を明示すればよい
  toy_data0 |> aov(value ~ factor, data = _) 
  toy_data0 |>
    aov(value ~ factor, data = _) |>
    broom::tidy()
  #'
  #' Monte-Carlo 実験
  mc_trial <- function(h0 = TRUE){
    if(h0) { # 帰無仮説が正しい場合
      tmp <-
        tibble(factor = fact,
               value = rnorm(length(fact), mean = 3, sd = 2)) |>
        aov(value ~ factor, data = _) |> broom::tidy()
    } else { # 対立仮説が正しい場合
      tmp <- 
        tibble(factor = fact, # 水準ごとに平均が異なる
               value = rnorm(length(fact), mean = 3, sd = 2) + alt) |>
        aov(value ~ factor, data = _) |> broom::tidy()
    }
    #' 分散分析表における factor 行の統計量とp値を返す
    return(c(statistic = tmp[1,5, drop = TRUE],
             p.value   = tmp[1,6, drop = TRUE]))
    #' 以下のように書いても良い
    #' return(tmp |> select(5:6) |> t() |> _[,1])
  }
  #'
  #' 帰無仮説が正しい場合のF統計量/p値の分布 (p値は一様分布になる)
  replicate(2000, mc_trial()) |>
    t() |> as_tibble() |> pivot_longer(everything()) |> # 描画用に変形
    ggplot(aes(x = value, fill = name)) +
    geom_histogram(show.legend = FALSE) +
    facet_wrap(vars(name), ncol = 2, scales = "free") + # それぞれ個別の座標で描画
    labs(title = "帰無仮説が正しい場合")
  #'
  #' 対立仮説が正しい場合のF統計量/p値の分布 (p値は小さな値に偏る)
  replicate(2000, mc_trial(h0 = FALSE)) |>
    t() |> as_tibble() |> pivot_longer(everything()) |> 
    ggplot(aes(x = value, fill = name)) +
    geom_histogram(show.legend = FALSE) +
    facet_wrap(vars(name), ncol = 2, scales = "free") + 
    labs(title = "帰無仮説が誤りの場合")
  #' ---------------------------------------------------------------------------
#+end_src

#+begin_src R :eval no :exports none
  #' ---------------------------------------------------------------------------
  #' @practice 一元配置分散分析
  #'
  #' 気候データによる例
  #' 曜日ごとの気温に差があるか否かを分散分析
  tw_data <- read_csv("data/tokyo_weather.csv") |>
    mutate(day_of_week = ordered(day_of_week, # 曜日を順序付き因子にする
                                 levels = wday(1:7, label = TRUE))) 
  #'
  #' 曜日ごとの分布を見るとともに平均・分散(標準偏差)を確認する
  tw_data |>
    ggplot(aes(x = day_of_week, y = temp)) +
    geom_boxplot(fill = "lavender") +
    labs(x = "曜日", y = "気温", title = "曜日ごとの気温の分布") 
  tw_data |>
    group_by(day_of_week) |>
    summarize(across(temp, list(mean = mean,
                                var = var,
                                sd = sd)))
  #'
  #' 曜日ごとの気温差に関する分散分析
  aov(temp ~ day_of_week, data = tw_data) # aovによる分析
  aov(temp ~ day_of_week, data = tw_data) |>
    summary() # 分散分析表の表示(棄却されない)
  aov(temp ~ day_of_week, data = tw_data) |>
    broom::tidy() # 分散分析表のデータフレーム (行・列の番号で必要な情報が取得できる)
  aov(temp ~ day_of_week, data = tw_data) |>
    model.tables(type = "means")   # 水準(曜日)ごとの平均値
  aov(temp ~ day_of_week, data = tw_data) |>
    model.tables(type = "effects") # 水準(曜日)ごとの効果
  #'
  #' 検定のみ実行する場合
  #' 級内の分散が等しいことを仮定
  oneway.test(temp ~ day_of_week, data = tw_data, var.equal = TRUE) 
  #' 級内の分散が等しいことが仮定できない場合はWelchの近似法による検定が行われる
  oneway.test(temp ~ day_of_week, data = tw_data) # 
  #'
  #' @notes
  #' 月ごとの気温に差があるか否かを分散分析 (棄却されるはず)
  #' 
  tw_data <- tw_data |> mutate(month = as_factor(month)) # 月を因子化
  tw_data |>
    ggplot(aes(x = month, y = temp)) +
    geom_boxplot(fill = "lavender") +
    labs(x = "月", y = "気温", title = "月ごとの気温の分布") 
  aov(temp ~ month, data = tw_data) |>
    summary() # 分散分析表の表示(棄却される)
  #'
  #' 曜日の因子化などは package::lubridate に含まれる関数が利用できる
  #' 曜日の文字列を得る方法
  wday(1:7, label = TRUE) # 省略名
  wday(1:7, label = TRUE, abbr = FALSE) # 正式名
  wday(2:8, label = TRUE) # 月曜から始まる文字列を得る場合
  wday(1:7, label = TRUE, week_start = 1) # 順序を月曜から始める場合
  #'
  #' 日付から曜日を得る方法
  tw_data |>
    mutate(date = as_date(paste(year,month,day, sep = "-")), # 日付に変換
           weekday = wday(date, label = TRUE), # 日付から曜日(順序付因子)を追加
           .before = year) # year列の前に付加
  #' ---------------------------------------------------------------------------
#+end_src


* 二元配置
** 二元配置の問題
- 因子が2種類ある場合
  - 一方の因子の水準の平均値に差があるか否かを検定
  - もう一方の因子の水準で平均値に差があるかは不問
- [[color:green][複数の薬の治験の問題]]
  #+begin_quote
  複数の薬の効能を複数の被験者に投与する実験
  - "薬の種類"と"被験者番号"の2種類の因子
  - "薬の種類"という因子での薬の効能の差を検証したい
  - "被験者番号"という因子で効能に差があることは許容したい
    (薬の効き目には個人差があると考えられるため)
  #+end_quote

** 二元配置のモデル
- 2種類の因子 \(A, B\)
  - 因子 \(A\) には \(a\) 個の水準 : \(A_1,\dotsc,A_a\)
  - 因子 \(B\) には \(b\) 個の水準 : \(B_1,\dotsc,B_b\)
  - 因子 \(A,B\) の水準がそれぞれ \(A_i,B_j\) である観測値 : \(Y_{ij}\)
  - [[color:orange][各水準ごとに1つの観測値が得られる一番簡単な場合を想定]]
- 観測データのモデル
  #+begin_quote
  \begin{equation}
    Y_{ij}=\alpha_i+\beta_j+\varepsilon_{ij}\quad
    (i=1,\dotsc,a;\;j=1,\dotsc,b).
  \end{equation}
  #+end_quote
- モデルの仮定
  - 因子 \(A,B\) の水準 \(A_i,B_j\) における効果
    \(\alpha_i,\beta_j\) は定数
  - \(\varepsilon_{ij}\) は独立同分布 (平均0, 分散 \(\sigma^2\) の正規分布)

** 二元配置の例
- [[color:green][複数の薬の治験の問題]]
  - 因子
    - 因子 \(A\) : "薬の種類"
    - 因子 \(B\) : "被験者番号"
  - 効果
    - \(\alpha_i\) : 薬 \(A_i\) の効能
    - \(\beta_j\) : 被験者 \(B_j\) 固有の薬の効きやすさ
  - 薬の効能に差があるか否かという検定

** 二元配置の検定
- 検定問題
  #+begin_quote
  因子 \(A\) の各水準の効果に差があるか否かを検定する

  (因子 \(B\) の効果は除いて検定したい)
  #+end_quote
  - 帰無仮説 : 因子 \(A\) の効果 \(\alpha_{i}\) に差はない
  - 対立仮説 : 因子 \(A\) の効果に差のあるものがある
    #+begin_quote
    \begin{equation}
      H_0:\alpha_1=\cdots=\alpha_a\quad\text{vs}\quad
      H_1:\text{ある\(i_1,i_2\)に対して}\alpha_{i_1}\neq\alpha_{i_2}.
    \end{equation}
    #+end_quote

** 分析の考え方
- データの変動から因子間での変動と観測誤差の変動を抽出して比較
- 各種平均 (\(n=ab\))
  #+begin_quote
  \begin{align}
    &\text{(全データの標本平均)}
    &\bar{Y}_{\cdot\cdot}&=\frac{1}{n}\sum_{i=1}^a\sum_{j=1}^{b}Y_{ij},\\
    &\text{(水準\(A_i\)の標本平均)}
    &\bar{Y}_{i\cdot}&=\frac{1}{b}\sum_{j=1}^bY_{ij}\quad
                       (i=1,\dotsc,a),\\
    &\text{(水準\(B_j\)の標本平均)}
    &\bar{Y}_{\cdot j}&=\frac{1}{a}\sum_{i=1}^aY_{ij}\quad
                        (j=1,\dotsc,b).
  \end{align}
  #+end_quote

#+reveal: split
- 因子効果の推定量としての標本平均
  #+begin_quote
  \begin{align}
    \bar{Y}_{i\cdot}
    &\to\alpha_i+\frac{1}{b}\sum_{j=1}^b\beta_j,\\
    \bar{Y}_{\cdot j}
    &\to\frac{1}{a}\sum_{i=1}^a\alpha_i+\beta_j,\\
    \bar{Y}_{\cdot\cdot}
    &\to\frac{1}{ab}\sum_{i=1}^a\sum_{j=1}^b(\alpha_i+\beta_j)=\frac{1}{a}\sum_{i=1}^a\alpha_i+\frac{1}{b}\sum_{j=1}^b\beta_j
  \end{align}
  \begin{equation}
    Y_{ij}-\bar{Y}_{i\cdot}
    -\bar{Y}_{\cdot j}+\bar{Y}_{\cdot\cdot}
    \to\varepsilon_{ij}
  \end{equation}
  #+end_quote

#+reveal: split
- 各種変動
  #+begin_quote
  \begin{align}
    &\text{(行間変動)}
    &SS_A&=b\sum_{i=1}^a(\bar{Y}_{i\cdot}-\bar{Y}_{\cdot\cdot})^2,\\
    &\text{(列間変動)}
    &SS_B&=a\sum_{j=1}^b(\bar{Y}_{\cdot j}-\bar{Y}_{\cdot\cdot})^2,\\
    &\text{(誤差変動)}
    &SS_E&=\sum_{i=1}^a\sum_{j=1}^b(Y_{ij}-\bar{Y}_{i\cdot}
           -\bar{Y}_{\cdot j}+\bar{Y}_{\cdot\cdot})^2.
  \end{align}
  #+end_quote
  - *行間変動* : 水準 \(A\) 内でのデータの変動
  - *列間変動* : 水準 \(B\) 内でのデータの変動

#+reveal: split
- 変動の分解
  #+begin_quote
  \begin{multline}
    \underbrace{\text{(全変動) }SS_T}_{\text{自由度 }ab-1}
    =\underbrace{\text{(行間変動) }SS_A}_{\text{自由度 }a-1}\\
    +\underbrace{\text{(列間変動) }SS_B}_{\text{自由度 }b-1}
    +\underbrace{\text{(誤差変動) }SS_E}_{\text{自由度 }(a-1)(b-1)}
  \end{multline}
  #+end_quote
- 帰無仮説 \(H_0\) が正しい場合
  - 変動 \(SS_A,SS_E\) はともに観測誤差のみが原因で生じる
  - 自由度を除けば本質的な違いはない
  - \(SS_A/(a{-}1)\), \(SS_E/(a{-}1)(b{-}1)\) は \(\sigma^2\) の不偏推定量

#+reveal: split
- 変動の分解
  #+begin_quote
  \begin{multline}
    \underbrace{\text{(全変動) }SS_T}_{\text{自由度 }ab-1}
    =\underbrace{\text{(行間変動) }SS_A}_{\text{自由度 }a-1}\\
    +\underbrace{\text{(列間変動) }SS_B}_{\text{自由度 }b-1}
    +\underbrace{\text{(誤差変動) }SS_E}_{\text{自由度 }(a-1)(b-1)}
  \end{multline}
  #+end_quote
- 対立仮説 \(H_1\) が正しい場合
  - 因子 \(A\) 内の水準間での効果 \(\alpha_1,\dotsc,\alpha_a\) の差に影響される
  - \(SS_A\) は \(SS_E\) より本質的に大きくなる

** 二元配置の検定
- 検定統計量
  #+begin_quote
  \begin{equation}
    F_A=\frac{SS_A/(a{-}1)}{SS_E/(a{-}1)(b{-}1)}
  \end{equation}
  #+end_quote
- 帰無仮説の下で次の事実が成り立つ
  - \(SS_A,SS_E\) は独立
  - \(SS_A\) は自由度 \(a{-}1\) の \(\chi^2\) 分布に従う
  - \(SS_E\) は自由度 \((a{-}1)(b{-}1)\) の \(\chi^2\) 分布に従う
- 帰無仮説の下 \(F_A\) は自由度 \(a{-}1,(a{-}1)(b{-}1)\) の \(F\) 分布に従う
- 対立仮説の下 \(F_A\) は大きな値をとるので右片側検定

** 棄却域を用いる場合
- 有意水準 : \(\alpha\in(0,1)\)
- 自由度 \(a{-}1,(a{-}1)(b{-}1)\) の \(F\) 分布
  - \(F_{1{-}\alpha}(a{-}1,(a{-}1)(b{-}1))\) : \(1{-}\alpha\) 分位点
- \(H_0\) の下で以下が成立
  #+begin_quote
  \begin{equation}
    P(F_A>F_{1{-}\alpha}(a{-}1,(a{-}1)(b{-}1)))=\alpha
  \end{equation}
  #+end_quote
- 第一種過誤の上限が \(\alpha\) となる棄却域
  #+begin_quote
  \begin{equation}
    R_{\alpha}=
    (F_{1{-}\alpha}(a{-}1,(a{-}1)(b{-}1)),\infty)
  \end{equation}
  #+end_quote

#+reveal: split
- データから検定統計量 \(F_A\) の値を計算
- 以下の場合，帰無仮説を棄却
  #+begin_quote
  \begin{equation}
    F_A>F_{1{-}\alpha}(a{-}1,(a{-}1)(b{-}1))
  \end{equation}
  #+end_quote

** @@latex:@@\(p\) 値を用いる場合
- \(p\) 値を計算 (右片側検定の場合の計算方法)
  #+begin_quote
  \begin{equation}
    \text{(\(p\) 値)}=\int_{F_A}^\infty f(x)dx
  \end{equation}
  #+end_quote
  - \(f\) は自由度 \(a{-}1,(a{-}1)(b{-}1)\) の \(F\) 分布の確率密度
- \(p\) 値が \(\alpha\) 未満なら帰無仮説を棄却

** 分散分析表 (二元配置の場合)
|------------------+--------------------+----------+----------------------------------------------+----------------+-------------------------------------------|
|                  | 自由度             | 平方和   | 平均平方和                                   | \(F\text{値}\) | \(p\text{値}\)                            |
|------------------+--------------------+----------+----------------------------------------------+----------------+-------------------------------------------|
| \(\text{因子}A\) | \(a{-}1\)          | \(SS_A\) | \(\displaystyle\frac{SS_A}{a{-}1}\)          | \(F_A\)        | \(\displaystyle\int_{F_A}^\infty f(x)dx\) |
| \(\text{因子}B\) | \(b{-}1\)          | \(SS_B\) | \(\displaystyle\frac{SS_B}{b{-}1}\)          | \(F_B\)        | \(\displaystyle\int_{F_B}^\infty f(x)dx\) |
|------------------+--------------------+----------+----------------------------------------------+----------------+-------------------------------------------|
| \(\text{誤差}\)  | \((a{-}1)(b{-}1)\) | \(SS_E\) | \(\displaystyle\frac{SS_E}{(a{-}1)(b{-}1)}\) |                |                                           |
|------------------+--------------------+----------+----------------------------------------------+----------------+-------------------------------------------|
- \(f\) は自由度 \(a{-}1,(a{-}1)(b{-}1)\) の \(F\) 分布の確率密度
  # 因子 \(A\) ではなく因子 \(B\) の水準間の平均の差に関心がある場合は，
  # \(A\) と \(B\) の役割を入れ替えて同様の議論を行えばよい  

** モデルの別表現
相対効果による定式化
- モデルの書き換え
  #+begin_quote
  \begin{align}
    \mu^*&=\bar{\alpha}+\bar{\beta},&
                                      \alpha^*_i&=\alpha_i-\bar{\alpha},&
                                                                          \beta^*_j&=\beta_j-\bar{\beta}\\
         &&\bar{\alpha}&=\frac{1}{a}\sum_{i=1}^a\alpha_i,
                                                &\bar{\beta}&=\frac{1}{b}\sum_{j=1}^b\beta_j
  \end{align}
  \begin{equation}
    Y_{ij}=\mu^*+\alpha^*_i+\beta^*_j+\varepsilon_{ij}\quad
    (i=1,\dotsc,a;\;j=1,\dotsc,b)
  \end{equation}
  \begin{equation}
    \text{ただし }\sum_{i=1}^a\alpha^*_i=\sum_{j=1}^b\beta^*_j=0
  \end{equation}
  #+end_quote

#+reveal: split
- 帰無仮説 \(H_0\) は以下と同等
  #+begin_quote
  \begin{equation}
    H_{0}:\alpha^*_1=\cdots=\alpha^*_a=0
  \end{equation}
  #+end_quote

** 分散分析の計算
- 基本書式 
  #+begin_src R :eval no :tangle no
    aov(formula, data)
    #' formula: 式，二元配置の場合は (観測値 ~ 因子 + 因子)
    #' data: データフレーム
  #+end_src
- 分散分析表なども同様


* 実習
:PROPERTIES:
:reveal_background: #fef4f4
:END:
** 練習問題
:PROPERTIES:
:reveal_background: #fef4f4
:END:
- ~package::datarium~ に含まれている
  ~jobsatisfaction~ データについて以下の問に答えよ．
  #+begin_quote
  性別 (~gender~) と
  学歴 (~education_level~) の違いによる
  仕事の満足度 (~score~) を収集したデータ
  #+end_quote
  - データを適当な方法で可視化しなさい．
  - それぞれの因子で満足度の平均に違いがあるか
    二元配置の分散分析を用いて検討しなさい．
  #+begin_src R :eval no :tangle no
    #' パッケージのインストールと読み込みは以下のように行うことができる
    install.packages("datarium") # インストール
    library("datarium") # 読み込み
  #+end_src

#+begin_src R :eval no :exports none
  #' ---------------------------------------------------------------------------
  #' @practice 二元配置分散分析
  #' 
  #' datarium::jobsatisfaction による例
  #' 性別(gender)と学歴(education_level)による仕事の満足度
  #' 満足度にそれぞれの因子の効果があるかを検証
  #' 
  #' install.packages("datarium") # 検定用のデータが集められている
  library("datarium") # packageの読み込み
  #'
  #' データの内容を確認
  head(jobsatisfaction) # データの一部を見る
  View(jobsatisfaction) # 左上ペインに表を表示する
  #'
  #' データの視覚化
  jobsatisfaction |> # 学歴ごとに性別を比較
    ggplot(aes(x = education_level, y = score, fill = gender)) +
    geom_boxplot()
  jobsatisfaction |> # 性別ごとに学歴を比較
    ggplot(aes(x = gender, y = score, fill = education_level)) +
    geom_boxplot()
  #' 二元配置分散分析
  aov(score ~ gender + education_level, data=jobsatisfaction) |>
    summary()
  aov(score ~ gender + education_level, data=jobsatisfaction) |>
    model.tables(type = "means")  
  aov(score ~ gender + education_level, data=jobsatisfaction) |>
    model.tables(type = "effects")
  #' ---------------------------------------------------------------------------
#+end_src


* 次回の予定
- 回帰分析
- 回帰係数の推定
  - 点推定
  - 区間推定
- 回帰係数の検定
  - 係数の有意性
- 決定係数


* Footnotes
* COMMENT ローカル変数
# Local Variables:
# org-latex-listings: minted
# End:
   
   
   
   
