---
title: "統計データ解析I"
subtitle: "第6講 練習問題"
date: "`r Sys.time()`"
format:
    html: 
      toc: true
      html-math-method: katex
      self-contained: true
      grid: 
        margin-width: 350px
execute: 
  echo: true
  warning: false
reference-location: margin
citation-location: margin
tbl-cap-location: margin
fig-cap-location: margin
editor: visual
editor_options: 
  chunk_output_type: console
---

## 準備

以下で利用する共通パッケージを読み込む．

```{r}
library(conflicted)  # 関数名の衝突を警告
conflicts_prefer(    # 優先的に使う関数を指定
    dplyr::filter(),
    dplyr::select(),
    dplyr::lag(),
    )
library(tidyverse)
```

## コイン投げの賭け

### 問題

以下のようなコイン投げの賭けを考える．

-   Alice と Bob の二人で交互にコインを投げ，最初に表が出た方を勝ちとする．

この賭けの勝率を求めるための確率シミュレーションを行いなさい．

## 確率シミュレーションの例題

以下の確率的な事象のシミュレーションを考えてみなさい．

### Buffon の針

2次元平面上に等間隔 $d$ で平行線が引いてある． 長さ $l$ の針を この平面上にランダムに落としたとき， 平行線と交わる確率はいくつか？ ただし $l\leq d$ とする．

### Monty Hall 問題

ゲームの参加者の前に閉まった3つのドアがあって， 1つのドアの後ろには景品の新車が， 2つのドアの後ろには外れを意味するヤギがいる． 参加者は新車が置かれたドアを当てると新車がもらえる．

参加者が1つのドアを選択した後， 司会のモンティが残りのドアのうちヤギがいるドアを開けてヤギを見せる． ここで参加者は，最初に選んだドアを残っているドアに変更してもよいと言われる．

参加者はドアを変更すべきだろうか？

### 秘書問題 (最適停止問題)

以下の条件のもと秘書を1人雇うとする．

-   $n$ 人が応募しており $n$ は既知とする．

-   応募者には $1$ 位から $n$ 位まで順位付けできる．

-   無作為な順序で1人ずつ面接を行う．

-   毎回の面接後その応募者を採用するか否かを決定する．

-   不採用にした応募者を後から採用することはできない．

"$r-1$ 番までの応募者は採用せず， $r$ 番以降の応募者でそれまで面接した中で最も良い者を採用する" という戦略を取るとき，最適な $r$ はいくつだろうか?
